name: Feature Request
description: Request a feature
title: "[Request]: "
labels: "request"
body:
- type: markdown
  attributes:
    value: Before requesting a feature, please search for existing [feature requests](https://github.com/iota-community/iota-wiki/labels/request) to avoid creating duplicates.
- type: textarea
  id: feature-description
  attributes:
    label: Feature description
    description: Briefly describe the feature that you are requesting.
  validations:
    required: true
- type: textarea
  id: motivation
  attributes:
    label: Motivation
    description: Explain why this feature is needed.
  validations:
    required: true
- type: textarea
  id: requirements
  attributes:
    label: Requirements
    description: Write a list of what you want this feature to do.  
    placeholder: |
        1.  
        2.  
        3.  
  validations:
    required: true
- type: textarea
  id: open-questions
  attributes:
    label: Open questions
    description: Use this section to ask any questions that are related to the feature.
- type: dropdown
  id: pull-request
  attributes:
    label: Are you planning to do it yourself in a pull request?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true

