git rm --cached -r next/external/cli-wallet/ &&
git rm --cached -r next/external/goshimmer/ &&
git rm --cached -r next/external/hornet/ &&
git rm --cached -r next/external/identity.rs/0.7-alpha &&
git rm --cached -r next/external/introduction-docs/ &&
git rm --cached -r next/external/inx-api-core-v0/ &&
git rm --cached -r next/external/inx-api-core-v1/ &&
git rm --cached -r next/external/inx-coordinator/ &&
git rm --cached -r next/external/inx-dashboard/ &&
git rm --cached -r next/external/inx-faucet/ &&
git rm --cached -r next/external/inx-indexer/ &&
git rm --cached -r next/external/inx-irc-metadata/ &&
git rm --cached -r next/external/inx-mqtt/ &&
git rm --cached -r next/external/inx-participation/ &&
git rm --cached -r next/external/inx-poi/ &&
git rm --cached -r next/external/inx-spammer/ &&
git rm --cached -r next/external/iota-2.0-research-specifications/ &&
git rm --cached -r next/external/stronghold.rs/develop &&
git rm --cached -r next/external/tips/ &&
git rm --cached -r next/external/wasp/