export const allFacets = [
  'language:en',
  [
    'docusaurus_tag:docs-get-started-current',
    'docusaurus_tag:docs-learn-current',
    'docusaurus_tag:docs-build-current',
    'docusaurus_tag:docs-iota-sdk-1-0-current',
    'docusaurus_tag:docs-identity-rs-1-0-current',
    'docusaurus_tag:docs-identity-rs-1-1-current',
    'docusaurus_tag:docs-identity-rs-1-2-current',
    'docusaurus_tag:docs-stronghold-rs-1-1-current',
    'docusaurus_tag:docs-apis-current',
    'docusaurus_tag:docs-cli-wallet-1-0-current',
    'docusaurus_tag:docs-community-current',
    'docusaurus_tag:docs-isc-v1-0-0-rc-6-current',
    'docusaurus_tag:docs-iota-sandbox-current',
    'docusaurus_tag:docs-introduction-docs-stardust-current',
    'docusaurus_tag:docs-chronicle-1-0-rc-2-current',
    'docusaurus_tag:docs-maintain-current',
    'docusaurus_tag:docs-hornet-2-0-current',
    'docusaurus_tag:docs-wasp-v1-0-0-rc-6-current',
    'docusaurus_tag:default',
    'docusaurus_tag:docs-iota-tips-current',
  ],
];

export const facetNamesJson = {
  'docusaurus_tag:docs-get-started-current': 'Get Started',
  'docusaurus_tag:docs-learn-current': 'Learn',
  'docusaurus_tag:default': 'Tutorial',
  'docusaurus_tag:docs-apis-current': 'Apis',
  'docusaurus_tag:docs-cli-wallet-1-0-current': 'Cli Wallet',
  'docusaurus_tag:docs-maintain-current': 'Maintain',
  'docusaurus_tag:docs-identity-rs-1-2-current': 'Identity.rs 1.2',
  'docusaurus_tag:docs-identity-rs-1-1-current': 'Identity.rs 1.1',
  'docusaurus_tag:docs-identity-rs-1-0-current': 'Identity.rs',
  'docusaurus_tag:docs-iota-sandbox-current': 'Iota',
  'docusaurus_tag:docs-build-current': 'Build',
  'docusaurus_tag:docs-isc-v1-0-0-rc-6-current': 'ISC',
  'docusaurus_tag:docs-stronghold-rs-1-1-current': 'Stronghold',
  'docusaurus_tag:docs-iota-core-1-0-current': 'Iota Core',
  'docusaurus_tag:docs-wasp-v1-0-0-rc-6-current': 'Wasp',
  'docusaurus_tag:docs-iota-sdk-1-0-current': 'Iota sdk',
  'docusaurus_tag:docs-hornet-2-0-current': 'Hornet',
  'docusaurus_tag:docs-introduction-docs-stardust-current': 'Stardust',
  'docusaurus_tag:docs-chronicle-1-0-rc-2-current': 'Chronicle',
  'docusaurus_tag:docs-community-current': 'Community',
  'docusaurus_tag:docs-iota-tips-current': 'Tips',
};
export const subFilters = [
  'Wasp',
  'Hornet',
  'Identity.rs',
  'Cli Wallet',
  'Apis',
  'Stronghold',
  'Iota sdk',
  'ISC',
  'Iota',
  'Stardust',
  'Chronicle',
  'Community',
];
export const subChildFilters = ['Identity.rs 1.2', 'Identity.rs 1.1'];
export const buildSubFilters = [
  'docusaurus_tag:docs-iota-sdk-1-0-current',
  'docusaurus_tag:docs-identity-rs-1-0-current',
  'docusaurus_tag:docs-identity-rs-1-2-current',
  'docusaurus_tag:docs-identity-rs-1-1-current',
  'docusaurus_tag:docs-stronghold-rs-1-1-current',
  'docusaurus_tag:docs-apis-current',
  'docusaurus_tag:docs-cli-wallet-1-0-current',
  'docusaurus_tag:docs-community-current',
  'docusaurus_tag:docs-isc-v1-0-0-rc-6-current',
  'docusaurus_tag:docs-iota-sandbox-current',
  'docusaurus_tag:docs-introduction-docs-stardust-current',
  'docusaurus_tag:docs-chronicle-1-0-rc-2-current',
];
export const identitySubFilters = [
  'docusaurus_tag:docs-identity-rs-1-2-current',
  'docusaurus_tag:docs-identity-rs-1-1-current',
];
export const maintainSubFilters = [
  'docusaurus_tag:docs-wasp-v1-0-0-rc-6-current',
  'docusaurus_tag:docs-hornet-2-0-current',
];
